# Generated by Django 2.1.7 on 2019-04-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190408_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='id',
            field=models.IntegerField(primary_key=1, serialize=False),
        ),
    ]
